services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000  # Bind to all network interfaces
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
