# Generated by Django 5.1.5 on 2025-01-28 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_marketuser_profile_picture'),
        ('Product', '0003_product_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificationbid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Product.bid')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_notifications', to='Auth.marketuser')),
            ],
        ),
    ]
