# Generated by Django 5.1.5 on 2025-01-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_notificationbid_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
