# Generated by Django 5.1.5 on 2025-02-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_notificationbid_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
