# Generated by Django 5.1.5 on 2025-02-16 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_bid_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('LBP', 'Lebanese Lira (ل.ل)')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Product.category'),
        ),
    ]
