# Generated by Django 5.1.5 on 2025-02-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_product_bid_end_time_product_buy_now_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('دولار أمريكي', 'دولار أمريكي'), ('الليرة اللبنانية (ل.ل)', 'الليرة اللبنانية (ل.ل)')], default='USD', max_length=23),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('عادي', 'عادي'), ('مزاد', 'مزاد')], default='simple', max_length=10),
        ),
    ]
