# Generated by Django 5.1.5 on 2025-02-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_alter_product_condition_alter_product_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('جديد', 'جديد'), ('مستعمل', 'مستعمل')], default='جديد', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('دولار أمريكي', 'دولار أمريكي'), ('الليرة اللبنانية (ل.ل)', 'الليرة اللبنانية (ل.ل)')], default='دولار أمريكي', max_length=23),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_type',
            field=models.CharField(choices=[('عادي', 'عادي'), ('مزاد', 'مزاد')], default='عادي', max_length=10),
        ),
    ]
