# Generated by Django 5.1.5 on 2025-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_in_history',
            field=models.BooleanField(default=False),
        ),
    ]
