# Generated by Django 5.1.5 on 2025-03-07 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_marketuser_created'),
        ('Chats', '0006_alter_notification_user_chatnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='Auth.marketuser'),
        ),
    ]
