# Generated by Django 5.1.5 on 2025-01-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_marketuser_registration_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Default_pfp.jpg', null=True, upload_to='profile_pic/'),
        ),
    ]
