# Generated by Django 5.1.5 on 2025-02-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_marketuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='auth_provider',
            field=models.CharField(default='email', max_length=10),
        ),
    ]
