# Generated by Django 5.1.5 on 2025-02-10 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_marketuser_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketuser',
            name='auth_provider',
        ),
    ]
