# Generated by Django 5.1.5 on 2025-02-11 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0007_marketuser_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketuser',
            name='registration_method',
        ),
    ]
