# Generated by Django 5.1.5 on 2025-02-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0008_remove_marketuser_registration_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
