# Generated by Django 5.1.5 on 2025-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0009_deletedaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
