# Generated by Django 5.1.5 on 2025-03-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0010_marketuser_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketuser',
            name='registration_method',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook'), ('apple', 'Apple ID')], max_length=10, null=True),
        ),
    ]
